name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: '1itt1eB0y/ip_derper'
          platform: 'github'
          ref: 'ip_derp'

      - name: modify
        run: |
          cd ..
          git clone -b main https://github.com/tailscale/tailscale ip_derp_origin --depth 1
          cd ip_derper_origin
          rm -rf .git*
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go
          cd ../ip_derp
          cp -rf ../ip_derp_origin/* .
          
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./
      #    publish_branch: ip_derper
      - uses: eunchurn/action-publish@v1.1.1
        env:    
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'ip_derp' #optional defaults to master
